### ISSUE TITLE
Buffer gets renamed incorrectly during activity

### ISSUE THREAD

**Issue by torhve** [rawdigits/wee-slack#192] opened 2016-03-21 11:54 UTC
I'm in a room called dev. Sometimes it gets renamed to >ev and stays that way for a few minutes and goes back to dev.

I'm told this is to signify activity.

Apart from the obvious bug in the buffer rename, could this behaviour be hidden behind a setting, perhaps?

**Comment by rawdigits** [comment] 2016-03-26 19:38
closing as a dupe of #146

**Closed by rawdigits** 2016-03-26 19:38 UTC
