### ISSUE TITLE
Ability to see real names

### ISSUE THREAD

**Issue by nertwork** [rawdigits/wee-slack#247] opened 2016-08-10 22:50 UTC
I'm wondering if there's a way to add in something like /whois username?

I haven't seen anything setup to do that yet and it's a feature that I need as we don't have a standard for usernames.

**Comment by tfheen** [comment] 2016-12-19 19:07
There currently isn't, no. This is a duplicate of #100, so I'll close this. It should be fairly easy to implement, so if you want to put together a PR, I would be happy to review it.

**Closed by tfheen** 2016-12-19 19:07 UTC
