### ISSUE TITLE
Crashes weechat

### ISSUE THREAD

**Issue by xiongchiamiov** [rawdigits/wee-slack#21] opened 2014-12-30 19:02 UTC
I finally got around to trying out wee-slack today (versus the irc bridge).  When I was connected, everything was great, but after a few minutes, weechat would crash (not while I was doing any particular thing).

As part of this experiment, I also upgraded weechat to the dev version (and tacked on a few extra compile options from last time), but I've been on irc for an hour or two now without any crashes, so my suspicions are on wee-slack.

I've got crash logs from weechat, but they seem to be mainly a dump of all my config options.  What's the best way for me to get debug information to you?

**Comment by mattrobenolt** [comment] 2015-01-16 07:06
+1 this is definitely wee-slack. I use weechat exclusively for IRC and never once had it crash. And same here, the backtrace dumped is completely useless.

**Comment by rawdigits** [comment] 2015-01-18 07:58
I've finally upgraded to the 1.1 release. No problems so far. I'm happy to help debug.

When it crashes, does weechat output a stack trace?

**Comment by rawdigits** [comment] 2015-01-21 15:56
I've talked with the weechat devs, and there is a bug in 1.1 that may cause crashes when buffers of the same name are created. Do you have any existing buffers (including server buffers) that have the same name as ones created by wee-slack?

**Comment by mattrobenolt** [comment] 2015-01-21 16:02
I did, yes.

**Comment by rawdigits** [comment] 2015-01-21 16:04
A fix is in weechat-dev, and will be in weechat 1.1.1. Does changing the buffer name mitigate the problem for you?

**Comment by mattrobenolt** [comment] 2015-01-21 16:06
Uh, it's not super trivial with the large number of buffers I have, but I'll try again once they push a new weechat-dev package to their PPA. Running the 01/13/2015 build right now.

**Comment by mattrobenolt** [comment] 2015-01-21 16:09
@rawdigits Are you referring to https://github.com/weechat/weechat/commit/9749b65f7e67bbee55e8708e571f5cff79b1bdbe ?

**Comment by rawdigits** [comment] 2015-01-21 17:05
I am, but that appears to only affect IRC buffers. Unfortunately, I'm not able to reproduce a crash yet. The above issue was affecting a friend that uses wee-slack, so I thought it might be related.

I'll chat with the devs about getting useful info from a crash dump. Would you be willing to create a (temporary) fresh .weechat directory with only wee-slack? I'd like to determine if this is a wee-slack interacting with something else issue or an issue that can be reproduced w/o other elements.

**Comment by mattrobenolt** [comment] 2015-01-21 17:07
I can try it out later.

**Comment by rawdigits** [comment] 2015-01-21 19:01
fixed here: https://github.com/rawdigits/wee-slack/commit/976b7e14c8398d04df1ea7d9e7ff213d9afb8abb

on a reload of the script, the buffers are closed by weechat, which triggers a message to slack to close the buffers. i wasn't handling this properly. this became a race condition which would result in a segfault because data is being written to a buffer that isn't there.

**Closed** 2015-01-22 01:01 UTC

**Comment by xiongchiamiov** [comment] 2015-02-12 18:52
Sorry I wasn't being responsive.  Thanks to @mattrobenolt for stepping in with some repro help, and of course @rawdigits for fixing a bug. :)

I updated and was using wee-slack yesterday without *too* many problems, but today it's being pretty finicky.  I'm on f04f94c81c2664b61ae755e6567ac60c82393910.

Here's the full text of weechat's output:

    [$]> weechat
    
    *** Very bad! WeeChat is crashing (SIGSEGV received)
    *** Full crash dump was saved to
    /Users/pearson/.weechat/weechat_crash_20150212_65540.log file.
    ***
    *** Please help WeeChat developers to fix this bug:
    ***   1. If you have a core file, please run:  gdb /path/to/weechat core
    ***      then issue command: "bt full" and send result to developers
    ***      (see user's guide for more info about report of crashes).
    ***   2. Otherwise send backtrace (below), only if it is a complete trace.
    ***      Keep the crash log file, just in case developers ask you some info
    ***      (be careful, private info like passwords may be in this file).
    
    ======= WeeChat backtrace =======
    (written by WeeChat 1.1.1, compiled on Feb  2 2015 10:22:54)
    ======= End of  backtrace =======
    zsh: abort      TERM=xterm-256color weechat

Let me poke around a little more and see if I can get you any more information.

**Comment by xiongchiamiov** [comment] 2015-02-12 19:33
I disabled my other plugins and it seems good so far (it's only been a few minutes, but I figured it was worthwhile information).  For reference, those plugins were:

* perl: `isgd.pl`
* python: `colorize_nicks.py`, `vimode.py`

**Comment by rawdigits** [comment] 2015-02-12 21:23
hmmm, i don't use any of the above. my first guess is colorize_nicks, since i mess with the nicklist a lot. can you do some process-of-elimination so i can focus on the right one?

**Comment by xiongchiamiov** [comment] 2015-02-12 22:09
It turned out to be a false positive - I got a crash a bit later on.  I figured out how to get gdb working on OS X, though, and ran weechat through there for a while until I got another crash (still with other plugins disabled).  Here's the `bt`:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fff9827d152 in strlen () from /usr/lib/system/libsystem_c.dylib
    (gdb) bt
    #0  0x00007fff9827d152 in strlen () from /usr/lib/system/libsystem_c.dylib
    #1  0x00000001000244a5 in gui_nicklist_send_signal ()
    #2  0x000000010002559a in gui_nicklist_nick_set ()
    #3  0x0000000102ab7b63 in weechat_python_api_nicklist_nick_set ()
    from /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    #4  0x0000000102b567e6 in PyEval_EvalFrameEx () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #5  0x0000000102b5962e in fast_function () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #6  0x0000000102b56400 in PyEval_EvalFrameEx () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #7  0x0000000102b5962e in fast_function () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #8  0x0000000102b56400 in PyEval_EvalFrameEx () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #9  0x0000000102b52d7a in PyEval_EvalCodeEx () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #10 0x0000000102af71ae in function_call () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #11 0x0000000102ad90ea in PyObject_Call () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #12 0x0000000102ad927b in call_function_tail () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #13 0x0000000102ad9210 in PyObject_CallFunction () from
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    #14 0x0000000102aa5c19 in weechat_python_exec () from
    /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    #15 0x0000000102aa80c5 in weechat_python_api_hook_fd_cb () from
    /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    #16 0x0000000100051da5 in hook_fd_exec ()
    #17 0x000000010006de2d in gui_main_loop ()
    #18 0x0000000100003297 in main ()
    (gdb)

I don't know if this matters, but this one was fairly soon after I woke my computer up from a network-killing sleep - other applications sometimes have issues trying to read from sockets that have been closed by the OS.  To be clear, though, I got a crash earlier when this wasn't the case.

And the full backtrace, if that's more helpful:

    #0  0x00007fff9827d152 in strlen () from /usr/lib/system/libsystem_c.dylib
    No symbol table info available.
    #1  0x00000001000244a5 in gui_nicklist_send_signal ()
    No symbol table info available.
    #2  0x000000010002559a in gui_nicklist_nick_set ()
    No symbol table info available.
    #3  0x0000000102ab7b63 in weechat_python_api_nicklist_nick_set ()
       from /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    No symbol table info available.
    #4  0x0000000102b567e6 in PyEval_EvalFrameEx () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #5  0x0000000102b5962e in fast_function () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #6  0x0000000102b56400 in PyEval_EvalFrameEx () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #7  0x0000000102b5962e in fast_function () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #8  0x0000000102b56400 in PyEval_EvalFrameEx () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #9  0x0000000102b52d7a in PyEval_EvalCodeEx () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #10 0x0000000102af71ae in function_call () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #11 0x0000000102ad90ea in PyObject_Call () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #12 0x0000000102ad927b in call_function_tail () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #13 0x0000000102ad9210 in PyObject_CallFunction () from /usr/local/Frameworks/Python.framework/Versions/2.7/Python
    No symbol table info available.
    #14 0x0000000102aa5c19 in weechat_python_exec () from /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    No symbol table info available.
    #15 0x0000000102aa80c5 in weechat_python_api_hook_fd_cb () from /usr/local/Cellar/weechat/1.1.1/lib/weechat/plugins/python.so
    No symbol table info available.
    #16 0x0000000100051da5 in hook_fd_exec ()
    No symbol table info available.
    #17 0x000000010006de2d in gui_main_loop ()
    No symbol table info available.
    #18 0x0000000100003297 in main ()
    No symbol table info available.

I'll keep running in gdb to see if I can get another crash and see if it's at the same place.

**Comment by xiongchiamiov** [comment] 2015-02-12 22:16
Ok, it's now pretty consistently crashing in the first few minutes, with either that bt or the one below, which makes me think it has something to do with the particular set of data that's coming in.

    Program received signal SIGSEGV, Segmentation fault.
    0x000000010005f0ac in string_shared_free ()
    (gdb) bt
    #0  0x000000010005f0ac in string_shared_free ()
    #1  0x0000000100025511 in gui_nicklist_nick_set ()
    #2  0x00000001022b7b63 in weechat_python_api_nicklist_nick_set ()
