### ISSUE TITLE
`here` referenced before assignment

### ISSUE THREAD

**Issue by alexbarton** [rawdigits/wee-slack#159] opened 2016-01-15 13:36 UTC
I get the following error in the WeeChat console:

```
–!– python: Fehlerhafte Argumente für die Funktion "nicklist_search_nick" (Skript: slack_extension)
–!– python: Fehlerhafte Argumente für die Funktion "nicklist_remove_nick" (Skript: slack_extension)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/net/arthur/home/alex/.weechat/python/autoload/wee_slack.py", line 1274, in slack_websocket_cb
python: stdout/stderr:     proc[function_name](message_json)
python: stdout/stderr:   File "/net/arthur/home/alex/.weechat/python/autoload/wee_slack.py", line 1330, in process_presence_change
python: stdout/stderr:     server.users.find(identifier).set_active()
python: stdout/stderr:   File "/net/arthur/home/alex/.weechat/python/autoload/wee_slack.py", line 793, in set_active
python: stdout/stderr:     channel.update_nicklist(self.identifier)
python: stdout/stderr:   File "/net/arthur/home/alex/.weechat/python/autoload/wee_slack.py", line 443, in update_nicklist
python: stdout/stderr:     w.nicklist_add_nick(self.channel_buffer, here, user.name, user.color_name, "", "", 1)
python: stdout/stderr: UnboundLocalError: local variable 'here' referenced before assignment
–!– python: Fehler in Funktion "slack_websocket_cb"
```

[ "Fehlerhafte Argumente für die Funktion" = wrong arguments for function ]
[ "Fehler in Funktion" = error in function ]

This is similar to #150, and seems to be related to setting/unsetting the "away" status.

**Comment by mrrsm** [comment] 2016-03-02 21:04
I have been getting this spammed in my logs lately as well.

**Comment by tfheen** [comment] 2016-03-05 11:18
Duplicate of #150, so closing.

**Closed by tfheen** 2016-03-05 11:18 UTC
