### ISSUE TITLE
[FEATURE] Prefix same nick, like weechat

### ISSUE THREAD

**Issue by fsegouin** [rawdigits/wee-slack#111] opened 2015-09-29 14:28 UTC
Hey guys,

Weechat has a nice feature to replace the nickname for a message with a prefix if the previous message in a buffer was from the same user.
```
/set weechat.look.prefix_same_nick "⤷"
```
It would be nice to have this option in wee-slack! Any idea on how difficult it would be?

**Example:**

![screen shot 2015-09-29 at 15 25 18](https://cloud.githubusercontent.com/assets/2843216/10167017/9bf2dd78-66be-11e5-8efe-60f6bd75051c.png)

**Comment by rawdigits** [comment] 2015-10-13 14:25
thanks! this is a dupe of #56 and there is a branch coming that will support this :)

**Closed by rawdigits** 2015-10-13 14:25 UTC
